### ISSUE TITLE
Add info about hotels + location

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/brainhackrennes-2018#7]

**Comment by cmaumet** [comment]
Info about location is implemented in https://github.com/Inria-Visages/brainhackrennes-2018/pull/8.

I don't know how to add all the hotels. Or maybe just a sentence saying that interested attendees can contact us for a list of suitable hotels?

What are your thoughts on this?

**Comment by cclairec** [comment]
Just saw this one. Where do we mention that they can contact us for any information about accommodations?

**Comment by cmaumet** [comment]
We have a list of hotels but I was not sure how this could fit on the website. You suggestion to add a comment with our contact for more info on accommodation sounds good! Do you want to send a PR?
